### ISSUE TITLE
Merge to Mainline

### ISSUE THREAD

**Issue by cancan101** [aleph7/caffe#4]
Any plans to merge these changes to mainline as configs in the Makefile along the lines of what https://github.com/BVLC/caffe/pull/561 added?

**Comment by aleph7** [comment]
The problem is that I ended up removing a bunch of libraries I didn't want to deal with (HDF5, OpenCV). I will contribute back once I figure out a way of disabling those without too much trouble. As it stands now you pretty much have to delete everything related to those libraries. See https://github.com/aleph7/caffe/commit/a07577bd32387f7957a1dfc7cbb5762b12f8cb3e for an example.

**Comment by cancan101** [comment]
Ideally with some combinations of Makefile changes and `ifdef`s iOS support can be added to mainline.
